#!/usr/bin/env bash
#
# Bash script for provisioning the MongoDB instances

set -e
set -x

function config(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_updated_python(){
  apt install -y python2.7 python-pip
}

function install_mtools(){
  apt install -y python-matplotlib python-psutil
  pip install mtools==1.5.3 pymongo==3.6.1 docopt faker==3.0.1
}

function install_mongod(){
  echo "Install MongoDB Enterprise Repository"
  wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  echo "deb [ arch=amd64,arm64,s390x ] http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-enterprise.list
  echo "Update Repositoryies"
  apt-get update -y

  echo "Install MongoDB Enterprise"
  apt-get install -y mongodb-enterprise
  echo "export LC_ALL=C" >> /root/.profile
}


function config(){
  apt-get update -y
  apt-get install --reinstall tzdata
  apt-get install -y wget psmisc iputils-ping
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | tee /etc/init/mongod.override
  # mongod path
  mkdir -p /home/vagrant
}

function install_mgeneratejs() {
  apt-get install curl -y
  curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
  bash nodesource_setup.sh
  apt-get install nodejs -y
  npm install -g npm@latest
  node -v
  npm -v
  npm install -g mgeneratejs
  rm nodesource_setup.sh
}

function install_xwindow() {
  # to render mplotlib
  apt-get install -y xorg
}

config
install_mongod
install_xwindow
install_updated_python
install_mtools
install_mgeneratejs
apt-get clean all
echo "DONE"
