#!/usr/bin/env bash
#
# Bash script for provisioning the MongoDB instances

set -e
set -x

function config(){
  export CLIENT_IP_ADDR=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | tail -1`
  export CLIENT_FQDN=`hostname`
  export CLIENT_NAME=`hostname | cut -d. -f 1 | tr '[:upper:]' '[:lower:]'`
  echo "Configuring /etc/hosts ..."
  echo "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4" > /etc/hosts
  echo "::1       localhost localhost.localdomain localhost6 localhost6.localdomain6" >> /etc/hosts
  echo "$CLIENT_IP_ADDR    $CLIENT_FQDN $CLIENT_NAME" >> /etc/hosts
}

function install_updated_python(){
    apt-get install python2.7 -y
    ln -fs /usr/bin/python2.7 /usr/bin/python
    apt-get install curl libcurl3 -y
    curl -o get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py
    python get-pip.py
    pip install --upgrade pip
    rm get-pip.py
}

function install_python_dependencies(){
    apt-get install -y python-dev
    apt-get install -y libfreetype6-dev pkg-config libpng12-dev

    pip install -r /root/requirements.txt
}

function install_mongod(){
  echo "Install MongoDB Enterprise Repository"
  wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | apt-key add -
  echo "deb [ arch=amd64,arm64,s390x ] http://repo.mongodb.com/apt/ubuntu xenial/mongodb-enterprise/4.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-enterprise.list
  echo "Update Repositoryies"
  apt-get update -y

  echo "Install MongoDB Enterprise"
  apt-get install -y mongodb-enterprise
  echo "export LC_ALL=C" >> /root/.profile
}


function config(){
  apt-get update -y
  apt-get install --reinstall tzdata
  apt-get install -y wget
  # disable THP
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/enabled
  echo -e "never" > /sys/kernel/mm/transparent_hugepage/defrag
  # disable mongod upstart service
  echo 'manual' | tee /etc/init/mongod.override
  # mongod path
  mkdir -p /home/vagrant
}

function install_mgeneratejs() {
  apt-get install curl -y
  curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
  bash nodesource_setup.sh
  apt-get install nodejs -y
  npm install -g npm@latest
  node -v
  npm -v
  npm install -g mgeneratejs
  rm nodesource_setup.sh
}


config
install_mongod
install_updated_python
install_python_dependencies
install_mgeneratejs
apt-get clean all
echo "DONE"
